### ISSUE TITLE
Improper Speaker Output

### ISSUE THREAD

**Issue by parth111999** [penglezos/device_xiaomi_raphael#10]
Can you please check what's up with right speaker output. It got recently fixed in latest VoltageOS you can diagnose the issue using this video.
https://youtu.be/6TWJaFD6R2s

**Comment by penglezos** [comment]
Just tested it can confirm the right channel on mono audio is broken. Not sure how this can affect day to day usage. I have to debug it myself since VoltageOS is source closed.

**Comment by ajay230ps** [comment]
This might help. 


https://github.com/Pc1598/kernel_xiaomi_raphael/commits/dev/DSP

**Comment by ajay230ps** [comment]
Comment from one of the dev.

![Screenshot_20230924-192920_Telegram](https://github.com/penglezos/device_xiaomi_raphael/assets/9684155/54398ada-cc73-4a5f-a8ce-f4dfa805003f)

**Comment by penglezos** [comment]
Fixed properly on the latest release.
