### ISSUE TITLE
app vault fade

### ISSUE THREAD

**Issue by loxdogs** [penglezos/device_xiaomi_raphael#15]
When you close app vault with home gesture, when you reopen it, closing fade remains.

https://youtube.com/shorts/yQmO3lg-_tY?feature=share

P.S. I have no idea, why it uploaded as shorts, maybe resolurion is a problem

**Comment by penglezos** [comment]
Cannot reproduce it. For LineageOS specific bugs please report : [here](https://wiki.lineageos.org/how-to/bugreport)
