### ISSUE TITLE
Not work video stream from ip camera in Digma smart life app

### ISSUE THREAD

**Issue by nioxkzn** [penglezos/device_xiaomi_raphael#17]
Youtube works fine, some video play normally. i tryed any versions of it app. 
Maybe some hardware acceleration is not working...

**Comment by penglezos** [comment]
Report will be ignored if you do not provide logs and a video.

**Comment by nioxkzn** [comment]
[logcat.log](https://github.com/penglezos/device_xiaomi_raphael/files/11302229/logcat.log)

https://user-images.githubusercontent.com/3958471/233805293-ed4a32ca-93e0-460c-9376-756dbd6fe68a.mp4

**Comment by nioxkzn** [comment]
Update to new release fw, all works fine now.  Video stream in it app works fine.
