### ISSUE TITLE
Adding native support to Ps5 controller

### ISSUE THREAD

**Issue by Armnoo** [penglezos/device_xiaomi_raphael#19]
So I heard they gave native support to Ps5 controller support in android 13. And the patches I used previously (lineage 17.0) is not working anymore :'(. I'm wondering if you can add native support to Ps5. 

Thank you for making this rom, it's really stable and feels fast in my phone.❤️

**Comment by penglezos** [comment]
The config is already enabled so I suspect it should be working. What patches did you previously used?

**Comment by Armnoo** [comment]
I use 1controller zip and other numerous patches to fix. But still it doesn't work . I even tried without any patches.

**Comment by Armnoo** [comment]
[1](https://forum.xda-developers.com/attachments/dualsenseps5-zip.5162591/) 
[2](https://drive.google.com/file/d/1-PpIejkNnc8XAap12WLni2yEvi5Spfb4/view) 
(This is the few I remember but all are very similar)

**Comment by Armnoo** [comment]
Here my key layouts
[Link](https://drive.google.com/drive/folders/1--d1j9ZKcqOcjDt31px0UvGfQix86fFH) 

(So I check it and I think the correct configuration turn to a fallback instead of the actual configuration and I tried to edit or delete the wrong configuration but it just reset itself)
