### ISSUE TITLE
Not an Issue, a query

### ISSUE THREAD

**Issue by Sparsa** [penglezos/device_xiaomi_raphael#2]
Are you planning to move to Lineage OS from arrow?

**Comment by penglezos** [comment]
Yes migration is completely done.

**Comment by Sparsa** [comment]
> Yes migration is completely done.

Cool. Are you planning for an official stat? I'm really enjoying your last arrow build. Will try the Lineage OS build.

**Comment by penglezos** [comment]
Not in my future plans yet.
