### ISSUE TITLE
Recovery isn't working 

### ISSUE THREAD

**Issue by trinoy-s** [penglezos/device_xiaomi_raphael#21]
Tried to flash ur rom using los recovery but after flashing rom and zip, I formatted but It didn't work my phone didn't boot and it came back to recovery,then I flashed ofx rec to flash

**Comment by parhithub** [comment]
Hi.
I have the same issue. I'm trying to update from [lineage-20.0-20221110-UNOFFICIAL-raphael](https://github.com/penglezos/device_xiaomi_raphael/releases/tag/lineage-20.0-20221110-UNOFFICIAL-raphael) but, after following the tutorial, it is not working. What have I done: sideload the LineageOS and the GAPPS then reboot and I have a bootloop. I have tried to make fastboot -w (but error) and trying to delete all the data as asked by the Lineage recovery but it still doesn't work.

**Comment by da3dsoul1** [comment]
Same for me, when I use the recovery and follow up all the steps I can't load android system all the time, wtf is wrong with this rom? Why not make it simple with TWRP or orangefox install? I really want to install this rom, but the method provided simply isnt working

**Comment by penglezos** [comment]
There is nothing wrong with this ROM or recovery. I have explained it over a gazillion times why some users fail to install properly the recovery and flash the ROM afterwards. The installation is straightforward and it's not limited to LineageOS recovery only meaning you can use any other recovery you like but support will not be provided by me.

**Comment by da3dsoul1** [comment]
Yeah, rom is awesome, I managed to flash it via orangefox that supports fbev1 decryption, so far so good. Though it was impossible to flash with recovery provided in your latest release, it always returns errors when flashing firmware, rom doesn't boot, even on xda people experience this and someone suggested that unofficial orangefox that worked for me and some others. Anyway thanks for the rom!

**Comment by parhithub** [comment]
As for me, Lineage recovery didn't work and neither did OrangeFox (or I didn't know what to do). I had to go through TWRP by booting on it via the "fastboot boot twrp.img" terminal, then Format data to get out of it. All in all, this version seems to be better than the previous one. The feedback here in no way detracts from the work done by penglezos and the other contributors; on the contrary, it's intended to help those who encounter the same problems.
