### ISSUE TITLE
Wireless Controller not working

### ISSUE THREAD

**Issue by dashdira** [penglezos/device_xiaomi_raphael#22]
![Screenshot_20230725-005459_Settings_1](https://github.com/penglezos/device_xiaomi_raphael/assets/83527158/68acedc3-bda5-4dd8-ac41-031bead8e7a2)

it appears and connected but I can't use it in any app, like psp or other emulator, it was working fine before previous build

**Comment by penglezos** [comment]
As you can see on the full changelog I did not changed anything related to wireless controller devices. Also without any logs I can't really figure out what's going on since I don't have a device like that to test it myself.

**Comment by dashdira** [comment]
my bad sorry, it was working fine in may build, broken since previous build, yes I'll try to catch some logs if possible
