### ISSUE TITLE
System updater behavior 

### ISSUE THREAD

**Issue by da3dsoul1** [penglezos/device_xiaomi_raphael#23]
I'm on a latest build, always update via adb sideload, just want to make sure if what I'm experiencing is normal or not. In system updater when I try to disable Update recovery it shows a toast that's it's impossible to do so, is it a bug or intended?
![image](https://github.com/penglezos/device_xiaomi_raphael/assets/111184581/7dc96926-636f-47bc-9b64-531628f89f01)

**Comment by penglezos** [comment]
You should be able to disable that. As it seems the Updater application lacks of internet permissions make sure you enable em.

**Comment by da3dsoul1** [comment]
Enabled permissions, update checking is working, but still can't disable update recovery function for some reason

**Comment by penglezos** [comment]
What recovery do you have installed LineageOS or something else?

**Comment by da3dsoul1** [comment]
> What recovery do you have installed LineageOS or something else?

I use ofox that supports fbev1, gonna try lineage recovery now and see it it works

**Comment by penglezos** [comment]
This feature only works with LineageOS recovery correctly.

**Comment by da3dsoul1** [comment]
> This feature only works with LineageOS recovery correctly.

Flashed latest lineage recovery from your release,  same thing

**Comment by penglezos** [comment]
![Screenshot_20230728-000150_Updater](https://github.com/penglezos/device_xiaomi_raphael/assets/7030531/2c26ba1a-9684-4ce3-b579-b924898b4327)

You are obviously doing something wrong.

**Comment by da3dsoul1** [comment]
Weird, gonna apply update from lineage recovery, if it doesn't work then I guess I have to clean flash

**Comment by da3dsoul1** [comment]
Okay, reapplying update through lineage recovery fixed the issue, gonna keep using it then. How stable it is when updating via Updater app? Both system and recovery updates I mean
