### ISSUE TITLE
Keyboard space remains after disabling navigation pill

### ISSUE THREAD

**Issue by da3dsoul1** [penglezos/device_xiaomi_raphael#26]
Could you please add an option to remove that space?
![photo_2023-08-30_19-38-11](https://github.com/penglezos/device_xiaomi_raphael/assets/111184581/d1462f6c-30de-4aa3-b525-9ff5c7d369ee)

I found an apk file that just updates some system app and removes the unwanted space completely.
![image](https://github.com/penglezos/device_xiaomi_raphael/assets/111184581/679e6d91-f20e-4a27-9929-4bf8e2f4b0cf)

Could this be implemented in your rom natively?

Here's an apk that I tried:
[Gesture navigation hide.zip](https://github.com/penglezos/device_xiaomi_raphael/files/12487875/Gesture.navigation.hide.zip)

**Comment by penglezos** [comment]
To answer your question: no. I like the default behavior.
