### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by da3dsoul1** [penglezos/device_xiaomi_raphael#28]
After prolonged phone uptime when you launch camera it will start lagging/stuttering(not the app itself, but camera, it's like you see 5fps video when you wave your phone around, as reboot fixes that, but after some time the lagging comes back. Any possibility of a fix or the rom has been abandoned?

**Comment by penglezos** [comment]
Hi! Thanks for your report but unfortunately I cannot reproduce your described issue. Did by any chance capture any log when that occurs? Do you use any custom kernel? Any kind of system modification?

**Comment by da3dsoul1** [comment]
Oh hi! I was using the rom without any modification on the provided lineag rcovery, forgot to capture any logs unfortunatley. I just clean flashed again and waiting for the bug to appear again, when I catch it I'll make sure to post the logs here
