### ISSUE TITLE
inti.rc is modified

### ISSUE THREAD

**Issue by Lazarus00001** [penglezos/device_xiaomi_raphael#29]
inti.rc is modified is detected by some banking apps due to this app didn't login

**Comment by penglezos** [comment]
Not sure what you are trying to say. First read [this](https://lineage.penglezos.dev/devices/raphael/#reporting-a-bug) on how to report a bug properly.

**Comment by monohitori** [comment]
> Not sure what you are trying to say. First read [this](https://lineage.penglezos.dev/devices/raphael/#reporting-a-bug) on how to report a bug properly.

hello, did you fix apn issue fully?
I haven't try your lastest build, because the previous one make my imei null

**Comment by penglezos** [comment]
> > Not sure what you are trying to say. First read [this](https://lineage.penglezos.dev/devices/raphael/#reporting-a-bug) on how to report a bug properly.
> 
> hello, did you fix apn issue fully? I haven't try your lastest build, because the previous one make my imei null

Yes? Do you even check the [releases](https://github.com/penglezos/device_xiaomi_raphael/releases/latest) or [XDA thread](https://xdaforums.com/t/rom-unofficial-lineageos-21-for-the-xiaomi-mi-9t-pro-redmi-k20-pro.4682559/post-89623886)?

**Comment by monohitori** [comment]
> > > Not sure what you are trying to say. First read [this](https://lineage.penglezos.dev/devices/raphael/#reporting-a-bug) on how to report a bug properly.
> > 
> > 
> > hello, did you fix apn issue fully? I haven't try your lastest build, because the previous one make my imei null
> 
> Yes? Do you even check the [releases](https://github.com/penglezos/device_xiaomi_raphael/releases/latest) or [XDA thread](https://xdaforums.com/t/rom-unofficial-lineageos-21-for-the-xiaomi-mi-9t-pro-redmi-k20-pro.4682559/post-89623886)?

I have just saw your latest build todat, I'll try now, and if find something wrong, I'll back to report it
thanks for coming back make Los for Raphael, after long time no update, I thought you're done with it😭

**Comment by penglezos** [comment]
> > > > Not sure what you are trying to say. First read [this](https://lineage.penglezos.dev/devices/raphael/#reporting-a-bug) on how to report a bug properly.
> > > 
> > > 
> > > hello, did you fix apn issue fully? I haven't try your lastest build, because the previous one make my imei null
> > 
> > 
> > Yes? Do you even check the [releases](https://github.com/penglezos/device_xiaomi_raphael/releases/latest) or [XDA thread](https://xdaforums.com/t/rom-unofficial-lineageos-21-for-the-xiaomi-mi-9t-pro-redmi-k20-pro.4682559/post-89623886)?
> 
> I have just saw your latest build todat, I'll try now, and if find something wrong, I'll back to report it thanks for coming back make Los for Raphael, after long time no update, I thought you're done with it😭

I never left actually. I was busy and building only for personal use.
