### ISSUE TITLE
Notification icons in the status bar moved

### ISSUE THREAD

**Issue by RDusr05** [penglezos/device_xiaomi_raphael#3]
Hello,

the icons of notifications are moved too far to the right in the status bar. 
I can fix the error by setting the clock to the left instead of the center and then setting the time to the center again. 

After a restart the problem comes back. 
![Screenshot_20221031-144208_Fennec](https://user-images.githubusercontent.com/76657659/199021936-1df74f7e-92ce-4e5f-a5f2-d20a857dbb1c.png)
![Screenshot_20221031-144242_LineageOS-Einstellungen](https://user-images.githubusercontent.com/76657659/199021940-5e63715a-1db9-4efb-91f1-4d101d3798d1.png)

**Comment by penglezos** [comment]
Hi,
I tried to reproduce your described issue but everything shows up normally. No problem on my end.

**Comment by sqozz** [comment]
I noticed the same issue but it doesn't seem to be consistent and only appears sometimes and also resolves itself. Is there any useful information we can provide when this issue happens?
I assume this is caused by moving the time into the middle of the status bar.
