### ISSUE TITLE
‘Prevent accidental wake’ feature not working 

### ISSUE THREAD

**Issue by ghost** [penglezos/device_xiaomi_raphael#30]
Prevent accidental wake up not working on my device.
Can you confirm it is same for you or just me?

**Comment by Lazarus00001** [comment]
> Prevent accidental wake up not working on my device. Can you confirm it is same for you or just me?

Work perfectly for me.

**Comment by penglezos** [comment]
> Prevent accidental wake up not working on my device. Can you confirm it is same for you or just me?

How exactly did you test it? It works for me.

**Comment by ghost** [comment]
I just covered the top part of screen before turning on the screen to test it. Proximity sensor is working fine as screen turns of during calls.

I did not modify anything (flashed rom + bitgapps).

If it is working for everyone then mine might have some random issue.
