### ISSUE TITLE
LSPosed

### ISSUE THREAD

**Issue by heloonihao** [penglezos/device_xiaomi_raphael#34]
My lsposed1.9.2 interface not work,But he can still detect the module and Send notifications
![Screenshot_20240729-161941_Shell](https://github.com/user-attachments/assets/3ff729e1-85aa-4970-9bf2-c5c32e3da1c1)

**Comment by penglezos** [comment]
From the Bug report section which clearly you did not read:

> Support is NOT provided if you: installed a custom recovery, decrypt your /data, installed a custom kernel, rooted your /system and installed any other mods.

**Comment by heloonihao** [comment]
[crash-zygote64-29_07-16-44-32_385.zip](https://github.com/user-attachments/files/16410006/crash-zygote64-29_07-16-44-32_385.zip)
here is log，using kernelsu（magisk is same crash），kernelsu only install zygisknext， zygisk-lsposed 1.9.2，android kernel using SOVIET-STAR

**Comment by heloonihao** [comment]
sorry about that
