### ISSUE TITLE
App security lock function

### ISSUE THREAD

**Issue by giallino64** [penglezos/device_xiaomi_raphael#37]
Hi penglezos,
I recently upgraded LOS from version 20 to 21 (build 20240820) following your instructions. I am also doing very well with version 21 and everything seems to be working fine. However, I would like to report that when an application is locked with the security options, its launch is conditioned by using the fingerprint, in my personal case, while when it is opened from a notification, the app opens normally without requiring unlocking. The "problem" was present in LOS 20 and now also in LOS 21.

**Comment by penglezos** [comment]
Hello @giallino64,

That's how "Protected Apps" are implemented in LineageOS. The code is implemented in Launcher instead system-wide. I know it's not the most efficient way but it is what it is until someone finds a better way.

**Comment by giallino64** [comment]
Hi @penglezos
Thanks for the information and also for the work you do for the community.
