### ISSUE TITLE
Device Certification fails

### ISSUE THREAD

**Issue by fallenjedi13** [penglezos/device_xiaomi_raphael#40]
As described in the title, the device certification fails. It is a fresh, clean install. Please check the attached pics. 
![Screenshot_20240924-122509_Trebuchet](https://github.com/user-attachments/assets/6756421d-bb5a-4e34-b1d0-26bd5cd09909)
![Screenshot_20240924-122533_Trebuchet](https://github.com/user-attachments/assets/534a1019-0bf4-4f89-9914-7c3674754a1b)

**Comment by penglezos** [comment]
I'm aware. Google literally killed the fingerprint yesterday.

**Comment by fallenjedi13** [comment]
Damn, google is hellbent on killing the developer community.

**Comment by razulian** [comment]
Is there a potential workaround for this problem that can be implemented?
