### ISSUE TITLE
Redundant zoom button in camera app

### ISSUE THREAD

**Issue by da3dsoul1** [penglezos/device_xiaomi_raphael#43]
In the default camera there are two buttons attributing to 1x zoom, is there any reason to that?
![image](https://github.com/user-attachments/assets/4e05f2ae-215b-426e-806d-a9025f478328)

**Comment by penglezos** [comment]
There is a visual glitch. The aperture can't handle the aux camera lenses' ID automatically. It is nothing major, but I will see what I can do.
