### ISSUE TITLE
Update Question 

### ISSUE THREAD

**Issue by monohitori** [penglezos/device_xiaomi_raphael#44]
Hello, I really like your work, I have using your rom long time as my daily driver on my second phone, but recently you didn't push any update, and the play store certificate is fail, I can't use WhatsApp on this phone, is there any way to fix this without using any mod? or do you have a plan releasing new build? at least small fix
I really sorry for asking this, I know you're really busy with your real life

**Comment by penglezos** [comment]
From the "What not to report" section of the [wiki](https://lineage.penglezos.dev/bugreport/):

> Ask for status updates - we can’t provide them (no ETA!).
