### ISSUE TITLE
Google Photos unlimited backup spoof NOT working

### ISSUE THREAD

**Issue by zinqshere** [penglezos/device_xiaomi_raphael#5]
The Google Photos app recognises the phone as a Pixel, but it just shows that it is compatible for unlimited backup and actually the feature doesn't work.

**Comment by penglezos** [comment]
Hi zinqshere,

Device is spoofed as a Pixel to bypass SafetyNet and not intended to enable unlimited backup functionality. Added to my todo list.

**Comment by penglezos** [comment]
Implemented for the next release if everything goes well.
