### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ajay230ps** [penglezos/device_xiaomi_raphael#6]
Hi

Have one feature request, add if possible, if its a hassle then ignore this request.

Add HD icon for volte in status bar. No customisation required.

And one question is Widevine L1 supported ? 

Example screenshot
![](https://i.ytimg.com/vi/hjcPLa3oWAY/maxresdefault.jpg)

**Comment by penglezos** [comment]
Hi,
There is no need for a HD icon in status bar to indicate VoLTE status since both native and Google dialer has one when you are in a call. 

Widevine L1 is working perfectly.

**Comment by ajay230ps** [comment]
Thank you 👍 😊
