### ISSUE TITLE
There is a bug, after flashed LineageOS 20, the recovery can not start

### ISSUE THREAD

**Issue by KudouShinnyan** [penglezos/device_xiaomi_raphael#9]
The OS I was using was PixelExperience Plus 13, at this time flash LineageOS recovery works fine, then after I used LineageOS recovery to flash linage-20.0-20230117-UNOFFICIAL- raphael.zip, I tried to reboot to recovery and it started fastboot directly, long press volume up and power button also fastboot, at this time whether it is reflash LineageOS recovery or TWRP can not change the status quo, then in fastboot input fastboot boot (LineageOS recovery file.img) did not smoothly start LineageOS recovery, but input fastboot boot (twrp file.img) could smoothly start TWRP, and when I flash PixelExperience Plus 13 again, I could use the regular method to Start Recvery, and after I reflash Lineage 20.0 again, it is the same as described just now

**Comment by penglezos** [comment]
Hi,
Thanks for submitting your issue. Did you follow the installation steps exactly? Formatting/wiping data from recovery? Typing fastboot -w after the described issue? Also on the previous rom your system was decrypted by any chance?

**Comment by KudouShinnyan** [comment]
> Hi, Thanks for submitting your issue. Did you follow the installation steps exactly? Formatting/wiping data from recovery? Typing fastboot -w after the described issue? Also on the previous rom your system was decrypted by any chance?

Every time I flash a different ROM, I format all the partitions
About decrypt, after each time I flashed the ROM and formatted the data, I flash this [Disable_Dm-Verity_ForceEncrypt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt)
I've reinstalled hundreds of apps on PixelExperience Plus 13, I'll try fastboot -w when I have time

**Comment by penglezos** [comment]
Never ever disable encryption why would you want that? That's probably the main cause of your problem. Please do so and don't forget to read and follow the installation instructions as described. Let me know.

**Comment by xbit11111111** [comment]
I had the same problem following the steps exactly. Now I flashed a different recovery and everything works fine.

**Comment by penglezos** [comment]
That's strange. I'm always following these steps without any problem.
